"""create chats table

Revision ID: 8a9adec6380e
Revises: 675ac5bb9053
Create Date: 2025-04-07 21:33:56.564935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9adec6380e'
down_revision: Union[str, None] = '675ac5bb9053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('config_type', sa.String(), server_default='database', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'config_type')
    # ### end Alembic commands ###
